[target.thumbv7em-none-eabihf]
# --no-location to make logs more readable
#runner = 'probe-rs run --chip STM32H7S3L8 --probe 0483:3754'
runner = 'probe-rs run --chip STM32H7S3L8 --probe 0483:3754 --no-location'

[build]
target = "thumbv7em-none-eabihf"

[net]
# SSH urls
git-fetch-with-cli = true

[env]
# adequate for a 4kB nvme-mi response
MCTP_ESTACK_MAX_MESSAGE = "4224"
